### ISSUE TITLE
Need to migrate temp zipfile storage to s3

### ISSUE THREAD

**Issue by jeremyrcoyle** [SUMSarizer/SUMSarizer#16]
Because Heroku.

https://devcenter.heroku.com/articles/s3-upload-python

**Comment by marcpare** [comment]
You can also toss them into a BLOB field in the DB: https://wiki.postgresql.org/wiki/BinaryFilesInDB#Storing_Binary_files_in_the_Database

**Comment by jeremyrcoyle** [comment]
That ended up working out great. Thanks for the suggestion!
