### ISSUE TITLE
Uploads stalling

### ISSUE THREAD

**Issue by ajaypillarisetti** [SUMSarizer/SUMSarizer#29]
Helping a colleague use SUMSarizer. Uploads of many files (165, ~2 MB) are stalling. Splitting the files into separate archives of ~50 files / 200 - 900KB each works fine. Left one 2MB file overnight, to make sure it wasn't my impatience. Chrome / OS X.

**Comment by marcpare** [comment]
Looks like it was nginx rejecting anything bigger than 2MB. Increased this limit and tested it.

Also added a tip to the upload section in case others end up exceeding the new limit (50MB)
