### ISSUE TITLE
A way to subset studies for labeling

### ISSUE THREAD

**Issue by SUMSarizer** [SUMSarizer/SUMSarizer#4]
We need to subset the data for each expert to label.
- Should different experts have the same or different subsets? Jeremy thinks same.
- How onerous should the labeling be? Maybe somewhere between 100 and 1000 cookstove days?
- Can the subsetting be smart enough to say when the machine isn't learning anymore? Maybe query the S&S matrix to determine when there are diminishing returns. We think there should be a minimum number of labeled days (>100 cookstove days).

**Comment by ajaypillarisetti** [comment]
Added a new database column (training) to table DataPoints -- should enable what we discussed about selecting random stove-weeks (or some equivalent) in R and then allowing multiple experts to label the same 'training' sets.

**Comment by jeremyrcoyle** [comment]
Training column is now populated with a random week on dataset upload. Route updated to optionally display only the training set. All templates updated to use this option. We'll probably want to add back in the option to display the full dataset, with labelling disabled.
