### ISSUE TITLE
Labelling Progress UI

### ISSUE THREAD

**Issue by SUMSarizer** [SUMSarizer/SUMSarizer#6]
Display some sort of progress indicator during labeling so users don't lose morale.

**Comment by jeremyrcoyle** [comment]
The data labelling page should have "done labelling" button that moves to the next csv file. The UI listing datasets to label should have check marks next to files that the user has already labelled

**Comment by jeremyrcoyle** [comment]
A list of files to label in a column to the left of the graph would be helpful

**Comment by ajaypillarisetti** [comment]
Altered the layout of the main presentation; added a column to the left of files associated with a given study (fixed-height div, scrollable-x); moved notes to this new left bar; edited css; added some JS to add a class to the active link; edited labeller.js to get the div width on pageload and adjust the graph accordingly. 

![screen shot 2015-04-21 at 12 32 33 am](https://cloud.githubusercontent.com/assets/3826288/7247399/f18b0bdc-e7bd-11e4-974c-899a49b0fd1d.png)

**Comment by ajaypillarisetti** [comment]
Closing this one for now.
