### ISSUE TITLE
Write a user agreement

### ISSUE THREAD

**Issue by SUMSarizer** [SUMSarizer/SUMSarizer#9]

**Comment by SUMSarizer** [comment]
this should be read at the time a new user is created.

**Comment by ajaypillarisetti** [comment]
add a placeholder for the EULA (filled with some riker ipsum!). Still need a EULA or agreement of some sort.

**Comment by daterdots** [comment]
Our use agreement should cover three categories of things: (1) we don't take any responsibility or provide any warranties. If our tool loses your data or gives bad results, we are not to blame. (2) You agree to let us see, use, and publish (anonymously) your data to improve our tool. (3) Finally, the copyright. I just gave us a Creative Commons 4.0 International License that allows others to share and improve upon our code given that they share their improvements. The use agreement draft I wrote is <a href="https://drive.google.com/open?id=0B97MSzGIfveENWNHQnlwbW9ubXc&authuser=0">here</a>.

Here is a little Creative Commons badge to put on the license page:
<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">SUMsarizer</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="http://gadgillab.berkeley.edu/people/daniel-wilson-research/" property="cc:attributionName" rel="cc:attributionURL">Daniel Wilson, Jeremy Coyle, and Ajay Pillarisetti</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.<br />Based on a work at <a xmlns:dct="http://purl.org/dc/terms/" href="https://github.com/SUMSarizer/" rel="dct:source">https://github.com/SUMSarizer/</a>.

**Comment by ajaypillarisetti** [comment]
Can't seem to access the draft user agreement. Added the CC badge / license link. Commit a803807
